[package]
name = "aris"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.12.0"
lazy_static = "1.4.0"
nom = "4.1.1"
petgraph = "0.4.13"
sha2 = "0.8.1"
varisat = "0.2.1"
xml-rs = "0.8.0"
itertools = "0.9.0"
frunk_core = "0.2.2"
strum = "0.18.0"
strum_macros = "0.18.0"
serde = { version = "^1.0", features = ["derive"] }
maplit = "1.0.2"

[build-dependencies]
version_check = "0.9"
