/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_rpi_aris_ArisNative */

#ifndef _Included_edu_rpi_aris_ArisNative
#define _Included_edu_rpi_aris_ArisNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_rpi_aris_ArisNative
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_rpi_aris_ArisNative_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
