/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_rpi_aris_ArisNative */

#ifndef _Included_edu_rpi_aris_ArisNative
#define _Included_edu_rpi_aris_ArisNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_rpi_aris_ArisNative
 * Method:    process_sentence
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_rpi_aris_ArisNative_process_1sentence
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
