#!/bin/bash
OS=$1
if [ "$1" = "linux" ] || [ "$1" = "" ]; then
	if [ "$1" = "" ]; then
		echo OS not specified defaulting to linux
		OS=linux
	fi
	CMAKE=cmake
	MAKE=make
elif [ "$1" = "win32" ]; then
	CMAKE=mingw32-cmake
	MAKE=mingw32-make
elif [ "$1" = "win64" ]; then
	CMAKE=mingw64-cmake
	MAKE=mingw64-make
elif [ "$1" = "all" ]; then
	$0 linux
	mv build build-linux
	$0 win32
	mv build build-win32
	$0 win64
	mv build build-win64
	exit 0
elif [ "$1" = "clean" ]; then
	rm -rf build*
	rm -rf bin*
	exit 0
else
	echo Unrecognized OS $1
	echo Options are: linux, win32, win64
	exit 1
fi

if [ -e "build-$OS" ]; then
	echo Removing old build directories
	rm -rf build-$OS
fi
CORES=`grep -c ^processor /proc/cpuinfo`

mkdir build-$OS
cd build-$OS
$CMAKE ..
$MAKE -j$CORES

cd ..
if [ -e "bin-$OS" ]; then
	echo Removing old bin directory
	rm -rf bin-$OS
fi
mkdir bin-$OS
cp build-$OS/aris* build-$OS/libaris* bin-$OS

if [ "$1" = "win32" ] || [ "$1" = "win64" ]; then
	cd bin-$OS
	python ../mingw-bundledlls.py aris.exe --copy
	cd ..
fi
