#!/bin/bash

#put this file in .git/hooks to auto update the version number on commit

CVERSION=$(cat libaris/src/main/resources/edu/rpi/aris/VERSION)
IFS='.' read -ra VER <<< "$CVERSION"
for i in "${!VER[@]}"; do
    if [ $i -eq $(expr ${#VER[@]} - 1) ]; then
        VERSION=$VERSION$(expr ${VER[$i]} + 1)
    else
        VERSION=$VERSION${VER[$i]}.
    fi
done
echo $VERSION > libaris/src/main/resources/edu/rpi/aris/VERSION
echo $VERSION > libassign/src/main/resources/edu/rpi/aris/assign/VERSION
git add libaris/src/main/resources/edu/rpi/aris/VERSION
git add libassign/src/main/resources/edu/rpi/aris/assign/VERSION
