#!/bin/bash

if ! id -u aris &> /dev/null; then
	useradd --system aris
fi

mkdir -p /var/lib/aris
mkdir -p /var/log/aris
mkdir -p /etc/aris.d
chown -R aris:aris /var/lib/aris
chown -R aris:aris /var/log/aris
chown -R aris:aris /usr/lib/aris
chmod -R 755 /var/lib/aris
chmod 755 /var/log/aris
chmod 755 /etc/aris.d

ln -s /usr/lib/aris/bin/* /usr/bin
ln -s /usr/lib/aris/default.cfg /etc/aris.d/99default.cfg

systemctl daemon-reload
