package edu.rpi.aris.assign.message;

public enum ErrorType {

    UNKNOWN_ERROR,
    PARSE_ERR,
    NOT_IMPLEMENTED,
    SQL_ERR,
    EXCEPTION,
    UNKNOWN_MSG_TYPE,
    IO_ERROR,
    INCORRECT_MSG_TYPE,
    NOT_FOUND,
    AUTH_FAIL,
    INVALID_PASSWORD,
    RESET_PASS,
    AUTH_WEAK_PASS,
    MISSING_MODULE,
    MODULE_ERROR,
    CANT_CHANGE_OWN_ROLE,
    FILE_TOO_LARGE,
    UNAUTHORIZED
}
