name: Deploy pages

on:
  push:
    branches:
      master

jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1
      - name: Update Rust
        run: rustup update
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build Aris with wasm-pack
        run: wasm-pack build web-app --target web --out-dir static/pkg
      - name: Delete web-app/static/pkg/.gitignore to prevent deployment from failing
        run: rm -f web-app/static/pkg/.gitignore
      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: web-app/static
