name: Tests

on: [push, pull_request]

jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
        env:
          # Deny compile warnings
          RUSTFLAGS: -D warnings

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v2
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
